source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SAUtils_Example', :exclusive => true do
  pod 'SAUtils', :path => '../'
end

target 'SAUtils_Tests', :exclusive => true do
  pod 'SAUtils', :path => '../'

  
end
